namespace: ansible
name: exoscale
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies: {}
repository: git@github.com:ansible-collection-migration/ansible.exoscale.git
documentation: https://github.com/ansible-collection-migration/ansible.exoscale/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.exoscale
issues: https://github.com/ansible-collection-migration/ansible.exoscale/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
